
networks:
  traefik-public:
    external: true

services:
  prelaunch:
    image: cafebuy-prelaunch:latest
    ports:
      - "80:80"
    deploy:
      replicas: 2
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.prelaunch.rule=Host(`www.cafebuy.es`)"
        - "traefik.http.routers.prelaunch.entrypoints=websecure"
        - "traefik.http.routers.prelaunch.tls=true"
        - "traefik.http.services.prelaunch.loadbalancer.server.port=80"
    networks:
      - traefik-public
