networks:
  traefik-public:
    name: traefik-public
    external: true
  seaweedfs:
    driver: overlay
    attachable: true

volumes:
  seaweedfs_volume:
    driver: local
  seaweedfs_filer_data:
    driver: local


configs:
  s3_conf:
    external: true



secrets:
  seaweedfs_s3_access_key:
    external: true
  seaweedfs_s3_secret_key:
    external: true
  seaweedfs_s3_username:
    external: true

services:
  master:
    image: chrislusf/seaweedfs:latest
    command: "master -ip=master -ip.bind=0.0.0.0 -port=9333"
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      labels:
        - "traefik.enable=true"
        - "traefik.docker.network=traefik-public"
        - "traefik.http.routers.seaweedfs-master.rule=Host(`www.cafebuy.es`) && PathPrefix(`/seaweedfs/master`)"
        - "traefik.http.routers.seaweedfs-master.entrypoints=websecure"
        - "traefik.http.routers.seaweedfs-master.tls.certresolver=myresolver"
        - "traefik.http.services.seaweedfs-master.loadbalancer.server.port=9333"
        - "traefik.http.middlewares.seaweedfs-master-strip.stripprefix.prefixes=/seaweedfs/master"
        - "traefik.http.middlewares.seaweedfs-master-strip.stripprefix.forceslash=false"
        - "traefik.http.routers.seaweedfs-master.middlewares=seaweedfs-master-strip"
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 3
    networks:
      - seaweedfs
      - traefik-public

  volume:
    image: chrislusf/seaweedfs:latest
    command: 'volume -mserver="master:9333" -ip.bind=0.0.0.0 -port=8080 -max=100 -publicUrl=volume:8080'
    volumes:
      - seaweedfs_volume:/data
    depends_on:
      - master
    deploy:
      mode: replicated
      replicas: 2
      endpoint_mode: dnsrr
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 3
    networks:
      - seaweedfs

  filer:
    image: chrislusf/seaweedfs:latest
    command: 'filer -master="master:9333" -ip.bind=0.0.0.0 -port=8888'
    volumes:
      - seaweedfs_filer_data:/data/filerldb2
    depends_on:
      - master
      - volume
    deploy:
      mode: replicated
      replicas: 1
      labels:
        - "traefik.enable=true"
        - "traefik.docker.network=traefik-public"
        - "traefik.http.routers.seaweedfs-filer.rule=Host(`www.cafebuy.es`) && PathPrefix(`/seaweedfs/filer`)"
        - "traefik.http.routers.seaweedfs-filer.entrypoints=websecure"
        - "traefik.http.routers.seaweedfs-filer.tls.certresolver=myresolver"
        - "traefik.http.services.seaweedfs-filer.loadbalancer.server.port=8888"
        - "traefik.http.middlewares.seaweedfs-filer-strip.stripprefix.prefixes=/seaweedfs/filer"
        - "traefik.http.middlewares.seaweedfs-filer-strip.stripprefix.forceslash=false"
        - "traefik.http.routers.seaweedfs-filer.middlewares=seaweedfs-filer-strip"
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 3
    networks:
      - seaweedfs
      - traefik-public

  s3:
    image: chrislusf/seaweedfs:latest
    entrypoint: ["/bin/sh"]
    command:
      - -c
      - |
        set -e
        echo "Verificando secrets..."
        test -f /run/secrets/seaweedfs_s3_access_key || { echo "Error: seaweedfs_s3_access_key no existe"; exit 1; }
        test -f /run/secrets/seaweedfs_s3_secret_key || { echo "Error: seaweedfs_s3_secret_key no existe"; exit 1; }
        test -f /run/secrets/seaweedfs_s3_username || { echo "Error: seaweedfs_s3_username no existe"; exit 1; }
        test -f /etc/seaweedfs/s3.json.template || { echo "Error: s3.json.template no existe"; exit 1; }

        echo "Leyendo secrets..."
        S3_ACCESS_KEY="$$(cat /run/secrets/seaweedfs_s3_access_key | tr -d '\n\r\t ')"
        S3_SECRET_KEY="$$(cat /run/secrets/seaweedfs_s3_secret_key | tr -d '\n\r\t ')"
        S3_USERNAME="$$(cat /run/secrets/seaweedfs_s3_username | tr -d '\n\r\t ')"

        echo "Verificando valores de secrets..."
        [ -n "$$S3_USERNAME" ] || { echo "Error: S3_USERNAME está vacío"; exit 1; }
        [ -n "$$S3_ACCESS_KEY" ] || { echo "Error: S3_ACCESS_KEY está vacío"; exit 1; }
        [ -n "$$S3_SECRET_KEY" ] || { echo "Error: S3_SECRET_KEY está vacío"; exit 1; }

        echo "Username: $$S3_USERNAME"
        echo "AccessKey length: $$(echo -n "$$S3_ACCESS_KEY" | wc -c)"
        echo "SecretKey length: $$(echo -n "$$S3_SECRET_KEY" | wc -c)"

        echo "Creando directorio de configuración..."
        mkdir -p /etc/seaweedfs

        echo "Generando configuracion S3 a partir de s3.json.template..."
        sed "s|\$SEAWEEDFS_S3_USERNAME|$S3_USERNAME|g; \
             s|\$SEAWEEDFS_S3_ACCESS_KEY|$S3_ACCESS_KEY|g; \
             s|\$SEAWEEDFS_S3_SECRET_KEY|$S3_SECRET_KEY|g" /etc/seaweedfs/s3.json.template > /etc/seaweedfs/s3.json


        echo "=== Configuración S3 generada ==="
        # cat /etc/seaweedfs/s3.json  # Commented out to avoid logging sensitive data
        echo "================================="

        echo "Verificando sintaxis JSON..."
        echo "$$(cat /etc/seaweedfs/s3.json)" | grep -q "{" || { echo "Error: Archivo JSON inválido"; exit 1; }

        echo "Esperando filer..."
        for i in {1..30}; do
          nc -z filer 8888 && break
          echo "Esperando filer, intento $$i..."
          sleep 1
        done
        [ $$? -eq 0 ] || { echo "Error: No se pudo conectar al filer"; exit 1; }

        echo "Iniciando S3..."
        exec weed s3 -filer=filer:8888 -ip.bind=0.0.0.0 -port=8333 -config=/etc/seaweedfs/s3.json -allowEmptyFolder=true -allowDeleteBucketNotEmpty=false
    secrets:
      - seaweedfs_s3_access_key
      - seaweedfs_s3_secret_key
      - seaweedfs_s3_username
    configs:
      - source: s3_conf
        target: /etc/seaweedfs/s3.json.template
    depends_on:
      - master
      - volume
      - filer
    deploy:
      mode: replicated
      replicas: 1
      labels:
        - "traefik.enable=true"
        - "traefik.docker.network=traefik-public"
        - "traefik.http.routers.seaweedfs-s3.rule=Host(`www.cafebuy.es`) && PathPrefix(`/seaweedfs/s3`)"
        - "traefik.http.routers.seaweedfs-s3.entrypoints=websecure"
        - "traefik.http.routers.seaweedfs-s3.tls.certresolver=myresolver"
        - "traefik.http.services.seaweedfs-s3.loadbalancer.server.port=8333"
        - "traefik.http.middlewares.seaweedfs-s3-strip.stripprefix.prefixes=/seaweedfs/s3"
        - "traefik.http.middlewares.seaweedfs-s3-strip.stripprefix.forceslash=false"
        - "traefik.http.middlewares.seaweedfs-s3-headers.headers.customrequestheaders.X-Forwarded-Proto=https"
        - "traefik.http.middlewares.seaweedfs-s3-headers.headers.customrequestheaders.X-Forwarded-Host=www.cafebuy.es"
        - "traefik.http.middlewares.seaweedfs-s3-headers.headers.customresponseheaders.Access-Control-Allow-Origin=*"
        - "traefik.http.middlewares.seaweedfs-s3-headers.headers.customresponseheaders.Access-Control-Allow-Methods=GET,POST,PUT,DELETE,HEAD,OPTIONS"
        - "traefik.http.middlewares.seaweedfs-s3-headers.headers.customresponseheaders.Access-Control-Allow-Headers=*"
        - "traefik.http.routers.seaweedfs-s3.middlewares=seaweedfs-s3-strip,seaweedfs-s3-headers"
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 3
    networks:
      - seaweedfs
      - traefik-public

  webdav:
    image: chrislusf/seaweedfs:latest
    command: 'webdav -filer="filer:8888" -port=7333'
    depends_on:
      - master
      - volume
      - filer
    deploy:
      mode: replicated
      replicas: 1
      labels:
        - "traefik.enable=true"
        - "traefik.docker.network=traefik-public"
        - "traefik.http.routers.seaweedfs-webdav.rule=Host(`www.cafebuy.es`) && PathPrefix(`/seaweedfs/webdav`)"
        - "traefik.http.routers.seaweedfs-webdav.entrypoints=websecure"
        - "traefik.http.routers.seaweedfs-webdav.tls.certresolver=myresolver"
        - "traefik.http.services.seaweedfs-webdav.loadbalancer.server.port=7333"
        - "traefik.http.middlewares.seaweedfs-webdav-strip.stripprefix.prefixes=/seaweedfs/webdav"
        - "traefik.http.middlewares.seaweedfs-webdav-strip.stripprefix.forceslash=false"
        - "traefik.http.routers.seaweedfs-webdav.middlewares=seaweedfs-webdav-strip"
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 3
    networks:
      - seaweedfs
      - traefik-public
