version: "3.8"

services:
  traefik:
    image: traefik:v3.1
    command:
      # Logging
      - "--log.level=INFO"
      - "--accesslog=true"
      
      # API and Dashboard
      - "--api.dashboard=true"
      - "--api.insecure=false"
      
      # Docker Swarm Provider
      - "--providers.swarm.endpoint=unix:///var/run/docker.sock"
      - "--providers.swarm.watch=true"
      - "--providers.swarm.exposedbydefault=false"
      - "--providers.swarm.network=traefik-public"
      
      # File Provider for dynamic configuration
      - "--providers.file.directory=/etc/traefik/dynamic"
      - "--providers.file.watch=true"
      
      # Entrypoints
      - "--entrypoints.web.address=:80"
      - "--entrypoints.web.http.redirections.entrypoint.to=websecure"
      - "--entrypoints.web.http.redirections.entrypoint.scheme=https"
      - "--entrypoints.web.http.redirections.entrypoint.permanent=true"
      - "--entrypoints.websecure.address=:443"
      
      # Global redirect to HTTPS
      - "--entrypoints.websecure.http.tls=true"
      
    ports:
      - target: 80
        published: 80
        protocol: tcp
        mode: ingress
      - target: 443
        published: 443
        protocol: tcp
        mode: ingress
        
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "traefik-config:/etc/traefik/dynamic:ro"
      
    secrets:
      - source: ssl_cert
        target: /etc/traefik/certs/cafebuy.crt
      - source: ssl_key
        target: /etc/traefik/certs/cafebuy.key
        
    networks:
      - traefik-public
      
    deploy:
      placement:
        constraints:
          - node.role == manager
      labels:
        # Disable auto-discovery to avoid port errors
        - "traefik.enable=false"
        
        # Dashboard routing
        - "traefik.http.routers.traefik-dashboard.rule=Host(`traefik.www.cafebuy.es`) && (PathPrefix(`/dashboard`) || PathPrefix(`/api`))"
        - "traefik.http.routers.traefik-dashboard.service=api@internal"
        - "traefik.http.routers.traefik-dashboard.entrypoints=websecure"
        - "traefik.http.routers.traefik-dashboard.tls=true"
        
        # Optional: Basic Auth for dashboard (uncomment if needed)
        # - "traefik.http.routers.traefik-dashboard.middlewares=dashboard-auth"
        # - "traefik.http.middlewares.dashboard-auth.basicauth.users=admin:$$2y$$05$$ejemploHashedPassword"

  # Servicio de ejemplo whoami
  whoami:
    image: traefik/whoami
    deploy:
      replicas: 2
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.whoami.rule=Host(`www.cafebuy.es`)"
        - "traefik.http.routers.whoami.entrypoints=websecure"
        - "traefik.http.routers.whoami.tls=true"
        - "traefik.http.services.whoami.loadbalancer.server.port=80"
        
        # Optional: Redirect www to non-www or vice versa
        # - "traefik.http.routers.whoami-redirect.rule=Host(`cafebuy.es`)"
        # - "traefik.http.routers.whoami-redirect.entrypoints=websecure"
        # - "traefik.http.routers.whoami-redirect.middlewares=redirect-to-www"
        # - "traefik.http.middlewares.redirect-to-www.redirectregex.regex=^https://cafebuy.es/(.*)"
        # - "traefik.http.middlewares.redirect-to-www.redirectregex.replacement=https://www.cafebuy.es/$${1}"
        # - "traefik.http.middlewares.redirect-to-www.redirectregex.permanent=true"
        
    networks:
      - traefik-public

networks:
  traefik-public:
    external: true

volumes:
  traefik-config:

secrets:
  ssl_cert:
    external: true
  ssl_key:
    external: true