version: "3.8"

services:
  traefik:
    image: traefik:v3.1
    command:
      - "--log.level=INFO"
      - "--accesslog=true"
      - "--api.dashboard=true"
      - "--api.insecure=false"
      - "--providers.swarm.endpoint=unix:///var/run/docker.sock"
      - "--providers.swarm.watch=true"
      - "--providers.swarm.exposedbydefault=false"
      - "--providers.swarm.network=traefik-public"
      - "--providers.file.directory=/etc/traefik/dynamic"
      - "--providers.file.watch=true"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.web.http.redirections.entrypoint.to=websecure"
      - "--entrypoints.web.http.redirections.entrypoint.scheme=https"
      - "--entrypoints.web.http.redirections.entrypoint.permanent=true"
      - "--entrypoints.websecure.address=:443"
      - "--entrypoints.websecure.http.tls=true"

    ports:
      - target: 80
        published: 80
        protocol: tcp
        mode: ingress
      - target: 443
        published: 443
        protocol: tcp
        mode: ingress

    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"

    secrets:
      - source: ssl_cert
        target: /etc/traefik/certs/cafebuy.crt
      - source: ssl_key
        target: /etc/traefik/certs/cafebuy.key

    configs:
      - source: tls_conf
        target: /etc/traefik/dynamic/tls.yaml

    networks:
      - traefik-public

    deploy:
      placement:
        constraints:
          - node.role == manager
      labels:
        - "traefik.enable=false"
        - "traefik.http.routers.traefik-dashboard.rule=Host(`traefik.www.cafebuy.es`) && (PathPrefix(`/dashboard`) || PathPrefix(`/api`))"
        - "traefik.http.routers.traefik-dashboard.service=api@internal"
        - "traefik.http.routers.traefik-dashboard.entrypoints=websecure"
        - "traefik.http.routers.traefik-dashboard.tls=true"

  whoami:
    image: traefik/whoami
    deploy:
      replicas: 2
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.whoami.rule=Host(`www.cafebuy.es`)"
        - "traefik.http.routers.whoami.entrypoints=websecure"
        - "traefik.http.routers.whoami.tls=true"
        - "traefik.http.services.whoami.loadbalancer.server.port=80"
    networks:
      - traefik-public

networks:
  traefik-public:
    external: true

secrets:
  ssl_cert:
    external: true
  ssl_key:
    external: true

configs:
  tls_conf:
    external: true
