networks:
  fresh_framework_network:
    external: true

services:
  server:
    image: fresh_framework_deno_server
    deploy:  # Configuración específica para Swarm
      mode: replicated
      replicas: 2  # Número de instancias (puedes escalar a más)
      restart_policy:
        condition: on-failure  # Reiniciar si falla
    ports:
      - "8000:8000"  # Puerto expuesto (host:contenedor)
    networks:
      - fresh_framework_network  # Red personalizada
