// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_well_known_assetlinks_json from "./routes/.well-known/assetlinks.json.ts";
import * as $_lang_license_routes_controller from "./routes/[lang]/[license]/_routes/_controller.ts";
import * as $_lang_license_routes_payload from "./routes/[lang]/[license]/_routes/_payload.ts";
import * as $_lang_license_routes_response from "./routes/[lang]/[license]/_routes/_response.ts";
import * as $_lang_license_routes_service from "./routes/[lang]/[license]/_routes/_service.ts";
import * as $_lang_license_routes_types from "./routes/[lang]/[license]/_routes/_types.ts";
import * as $_lang_license_routes_utils from "./routes/[lang]/[license]/_routes/_utils.ts";
import * as $_lang_license_routes_validation from "./routes/[lang]/[license]/_routes/_validation.ts";
import * as $_lang_middleware from "./routes/[lang]/_middleware.ts";
import * as $_lang_admin_middleware from "./routes/[lang]/admin/_middleware.ts";
import * as $_lang_admin_routes_controller from "./routes/[lang]/admin/_routes/_controller.ts";
import * as $_lang_admin_routes_payload from "./routes/[lang]/admin/_routes/_payload.ts";
import * as $_lang_admin_routes_response from "./routes/[lang]/admin/_routes/_response.ts";
import * as $_lang_admin_routes_service from "./routes/[lang]/admin/_routes/_service.ts";
import * as $_lang_admin_routes_types from "./routes/[lang]/admin/_routes/_types.ts";
import * as $_lang_admin_routes_utils from "./routes/[lang]/admin/_routes/_utils.ts";
import * as $_lang_admin_routes_validation from "./routes/[lang]/admin/_routes/_validation.ts";
import * as $_lang_admin_index from "./routes/[lang]/admin/index.tsx";
import * as $_lang_app_routes_controller from "./routes/[lang]/app/_routes/_controller.ts";
import * as $_lang_app_routes_payload from "./routes/[lang]/app/_routes/_payload.ts";
import * as $_lang_app_routes_response from "./routes/[lang]/app/_routes/_response.ts";
import * as $_lang_app_routes_service from "./routes/[lang]/app/_routes/_service.ts";
import * as $_lang_app_routes_types from "./routes/[lang]/app/_routes/_types.ts";
import * as $_lang_app_routes_utils from "./routes/[lang]/app/_routes/_utils.ts";
import * as $_lang_app_routes_validation from "./routes/[lang]/app/_routes/_validation.ts";
import * as $_lang_app_index from "./routes/[lang]/app/index.tsx";
import * as $_lang_business_app_license_routes_controller from "./routes/[lang]/business/app/[license]/_routes/_controller.ts";
import * as $_lang_business_app_license_routes_payload from "./routes/[lang]/business/app/[license]/_routes/_payload.ts";
import * as $_lang_business_app_license_routes_response from "./routes/[lang]/business/app/[license]/_routes/_response.ts";
import * as $_lang_business_app_license_routes_service from "./routes/[lang]/business/app/[license]/_routes/_service.ts";
import * as $_lang_business_app_license_routes_types from "./routes/[lang]/business/app/[license]/_routes/_types.ts";
import * as $_lang_business_app_license_routes_utils from "./routes/[lang]/business/app/[license]/_routes/_utils.ts";
import * as $_lang_business_app_license_routes_validation from "./routes/[lang]/business/app/[license]/_routes/_validation.ts";
import * as $_lang_business_app_middleware from "./routes/[lang]/business/app/_middleware.ts";
import * as $_lang_business_app_employee_index from "./routes/[lang]/business/app/employee/index.tsx";
import * as $_lang_business_app_index from "./routes/[lang]/business/app/index.tsx";
import * as $_lang_business_app_license from "./routes/[lang]/business/app/license.tsx";
import * as $_lang_business_app_step_before from "./routes/[lang]/business/app/step_before.tsx";
import * as $_lang_business_web_app_middleware from "./routes/[lang]/business/web/app/_middleware.ts";
import * as $_lang_business_web_app_routes_controller from "./routes/[lang]/business/web/app/_routes/_controller.ts";
import * as $_lang_business_web_app_routes_payload from "./routes/[lang]/business/web/app/_routes/_payload.ts";
import * as $_lang_business_web_app_routes_response from "./routes/[lang]/business/web/app/_routes/_response.ts";
import * as $_lang_business_web_app_routes_service from "./routes/[lang]/business/web/app/_routes/_service.ts";
import * as $_lang_business_web_app_routes_types from "./routes/[lang]/business/web/app/_routes/_types.ts";
import * as $_lang_business_web_app_routes_utils from "./routes/[lang]/business/web/app/_routes/_utils.ts";
import * as $_lang_business_web_app_routes_validation from "./routes/[lang]/business/web/app/_routes/_validation.ts";
import * as $_lang_business_web_app_analitics_routes_controller from "./routes/[lang]/business/web/app/analitics/_routes/_controller.ts";
import * as $_lang_business_web_app_analitics_routes_payload from "./routes/[lang]/business/web/app/analitics/_routes/_payload.ts";
import * as $_lang_business_web_app_analitics_routes_response from "./routes/[lang]/business/web/app/analitics/_routes/_response.ts";
import * as $_lang_business_web_app_analitics_routes_service from "./routes/[lang]/business/web/app/analitics/_routes/_service.ts";
import * as $_lang_business_web_app_analitics_routes_types from "./routes/[lang]/business/web/app/analitics/_routes/_types.ts";
import * as $_lang_business_web_app_analitics_routes_utils from "./routes/[lang]/business/web/app/analitics/_routes/_utils.ts";
import * as $_lang_business_web_app_analitics_routes_validation from "./routes/[lang]/business/web/app/analitics/_routes/_validation.ts";
import * as $_lang_business_web_app_analitics_index from "./routes/[lang]/business/web/app/analitics/index.tsx";
import * as $_lang_business_web_app_configurations_routes_controller from "./routes/[lang]/business/web/app/configurations/_routes/_controller.ts";
import * as $_lang_business_web_app_configurations_routes_payload from "./routes/[lang]/business/web/app/configurations/_routes/_payload.ts";
import * as $_lang_business_web_app_configurations_routes_response from "./routes/[lang]/business/web/app/configurations/_routes/_response.ts";
import * as $_lang_business_web_app_configurations_routes_service from "./routes/[lang]/business/web/app/configurations/_routes/_service.ts";
import * as $_lang_business_web_app_configurations_routes_types from "./routes/[lang]/business/web/app/configurations/_routes/_types.ts";
import * as $_lang_business_web_app_configurations_routes_utils from "./routes/[lang]/business/web/app/configurations/_routes/_utils.ts";
import * as $_lang_business_web_app_configurations_routes_validation from "./routes/[lang]/business/web/app/configurations/_routes/_validation.ts";
import * as $_lang_business_web_app_configurations_index from "./routes/[lang]/business/web/app/configurations/index.tsx";
import * as $_lang_business_web_app_dashboard_routes_controller from "./routes/[lang]/business/web/app/dashboard/_routes/_controller.ts";
import * as $_lang_business_web_app_dashboard_routes_payload from "./routes/[lang]/business/web/app/dashboard/_routes/_payload.ts";
import * as $_lang_business_web_app_dashboard_routes_response from "./routes/[lang]/business/web/app/dashboard/_routes/_response.ts";
import * as $_lang_business_web_app_dashboard_routes_service from "./routes/[lang]/business/web/app/dashboard/_routes/_service.ts";
import * as $_lang_business_web_app_dashboard_routes_types from "./routes/[lang]/business/web/app/dashboard/_routes/_types.ts";
import * as $_lang_business_web_app_dashboard_routes_utils from "./routes/[lang]/business/web/app/dashboard/_routes/_utils.ts";
import * as $_lang_business_web_app_dashboard_routes_validation from "./routes/[lang]/business/web/app/dashboard/_routes/_validation.ts";
import * as $_lang_business_web_app_dashboard_analistics_index from "./routes/[lang]/business/web/app/dashboard/analistics/index.tsx";
import * as $_lang_business_web_app_dashboard_configuration_index from "./routes/[lang]/business/web/app/dashboard/configuration/index.tsx";
import * as $_lang_business_web_app_dashboard_index from "./routes/[lang]/business/web/app/dashboard/index.tsx";
import * as $_lang_business_web_app_dashboard_orders_index from "./routes/[lang]/business/web/app/dashboard/orders/index.tsx";
import * as $_lang_business_web_app_dashboard_reports_index from "./routes/[lang]/business/web/app/dashboard/reports/index.tsx";
import * as $_lang_business_web_app_dashboard_warehouse_index from "./routes/[lang]/business/web/app/dashboard/warehouse/index.tsx";
import * as $_lang_business_web_app_index from "./routes/[lang]/business/web/app/index.tsx";
import * as $_lang_business_web_app_multibusiness_routes_controller from "./routes/[lang]/business/web/app/multibusiness/_routes/_controller.ts";
import * as $_lang_business_web_app_multibusiness_routes_payload from "./routes/[lang]/business/web/app/multibusiness/_routes/_payload.ts";
import * as $_lang_business_web_app_multibusiness_routes_response from "./routes/[lang]/business/web/app/multibusiness/_routes/_response.ts";
import * as $_lang_business_web_app_multibusiness_routes_service from "./routes/[lang]/business/web/app/multibusiness/_routes/_service.ts";
import * as $_lang_business_web_app_multibusiness_routes_types from "./routes/[lang]/business/web/app/multibusiness/_routes/_types.ts";
import * as $_lang_business_web_app_multibusiness_routes_utils from "./routes/[lang]/business/web/app/multibusiness/_routes/_utils.ts";
import * as $_lang_business_web_app_multibusiness_routes_validation from "./routes/[lang]/business/web/app/multibusiness/_routes/_validation.ts";
import * as $_lang_business_web_app_multibusiness_index from "./routes/[lang]/business/web/app/multibusiness/index.tsx";
import * as $_lang_business_web_app_users_routes_controller from "./routes/[lang]/business/web/app/users/_routes/_controller.ts";
import * as $_lang_business_web_app_users_routes_payload from "./routes/[lang]/business/web/app/users/_routes/_payload.ts";
import * as $_lang_business_web_app_users_routes_response from "./routes/[lang]/business/web/app/users/_routes/_response.ts";
import * as $_lang_business_web_app_users_routes_service from "./routes/[lang]/business/web/app/users/_routes/_service.ts";
import * as $_lang_business_web_app_users_routes_types from "./routes/[lang]/business/web/app/users/_routes/_types.ts";
import * as $_lang_business_web_app_users_routes_utils from "./routes/[lang]/business/web/app/users/_routes/_utils.ts";
import * as $_lang_business_web_app_users_routes_validation from "./routes/[lang]/business/web/app/users/_routes/_validation.ts";
import * as $_lang_business_web_app_users_index from "./routes/[lang]/business/web/app/users/index.tsx";
import * as $_lang_business_web_www_routes_controller from "./routes/[lang]/business/web/www/_routes/_controller.ts";
import * as $_lang_business_web_www_routes_payload from "./routes/[lang]/business/web/www/_routes/_payload.ts";
import * as $_lang_business_web_www_routes_response from "./routes/[lang]/business/web/www/_routes/_response.ts";
import * as $_lang_business_web_www_routes_service from "./routes/[lang]/business/web/www/_routes/_service.ts";
import * as $_lang_business_web_www_routes_types from "./routes/[lang]/business/web/www/_routes/_types.ts";
import * as $_lang_business_web_www_routes_utils from "./routes/[lang]/business/web/www/_routes/_utils.ts";
import * as $_lang_business_web_www_routes_validation from "./routes/[lang]/business/web/www/_routes/_validation.ts";
import * as $_lang_business_web_www_about_index from "./routes/[lang]/business/web/www/about/index.tsx";
import * as $_lang_business_web_www_careers_index from "./routes/[lang]/business/web/www/careers/index.tsx";
import * as $_lang_business_web_www_contact_index from "./routes/[lang]/business/web/www/contact/index.tsx";
import * as $_lang_business_web_www_cookies_index from "./routes/[lang]/business/web/www/cookies/index.tsx";
import * as $_lang_business_web_www_help_index from "./routes/[lang]/business/web/www/help/index.tsx";
import * as $_lang_business_web_www_history_index from "./routes/[lang]/business/web/www/history/index.tsx";
import * as $_lang_business_web_www_index from "./routes/[lang]/business/web/www/index.tsx";
import * as $_lang_business_web_www_login_routes_controller from "./routes/[lang]/business/web/www/login/_routes/_controller.ts";
import * as $_lang_business_web_www_login_routes_payload from "./routes/[lang]/business/web/www/login/_routes/_payload.ts";
import * as $_lang_business_web_www_login_routes_response from "./routes/[lang]/business/web/www/login/_routes/_response.ts";
import * as $_lang_business_web_www_login_routes_service from "./routes/[lang]/business/web/www/login/_routes/_service.ts";
import * as $_lang_business_web_www_login_routes_types from "./routes/[lang]/business/web/www/login/_routes/_types.ts";
import * as $_lang_business_web_www_login_routes_utils from "./routes/[lang]/business/web/www/login/_routes/_utils.ts";
import * as $_lang_business_web_www_login_routes_validation from "./routes/[lang]/business/web/www/login/_routes/_validation.ts";
import * as $_lang_business_web_www_login_index from "./routes/[lang]/business/web/www/login/index.tsx";
import * as $_lang_business_web_www_partners_global_index from "./routes/[lang]/business/web/www/partners/global/index.tsx";
import * as $_lang_business_web_www_partners_local_index from "./routes/[lang]/business/web/www/partners/local/index.tsx";
import * as $_lang_business_web_www_pricing_index from "./routes/[lang]/business/web/www/pricing/index.tsx";
import * as $_lang_business_web_www_privacy_index from "./routes/[lang]/business/web/www/privacy/index.tsx";
import * as $_lang_business_web_www_status_index from "./routes/[lang]/business/web/www/status/index.tsx";
import * as $_lang_business_web_www_team_index from "./routes/[lang]/business/web/www/team/index.tsx";
import * as $_lang_business_web_www_terms_index from "./routes/[lang]/business/web/www/terms/index.tsx";
import * as $_lang_client_step_before_routes_controller from "./routes/[lang]/client/[step_before]/_routes/_controller.ts";
import * as $_lang_client_step_before_routes_payload from "./routes/[lang]/client/[step_before]/_routes/_payload.ts";
import * as $_lang_client_step_before_routes_response from "./routes/[lang]/client/[step_before]/_routes/_response.ts";
import * as $_lang_client_step_before_routes_service from "./routes/[lang]/client/[step_before]/_routes/_service.ts";
import * as $_lang_client_step_before_routes_types from "./routes/[lang]/client/[step_before]/_routes/_types.ts";
import * as $_lang_client_step_before_routes_utils from "./routes/[lang]/client/[step_before]/_routes/_utils.ts";
import * as $_lang_client_step_before_routes_validation from "./routes/[lang]/client/[step_before]/_routes/_validation.ts";
import * as $_lang_client_app_private_step_before_routes_controller from "./routes/[lang]/client/app/private/[step_before]/_routes/_controller.ts";
import * as $_lang_client_app_private_step_before_routes_payload from "./routes/[lang]/client/app/private/[step_before]/_routes/_payload.ts";
import * as $_lang_client_app_private_step_before_routes_response from "./routes/[lang]/client/app/private/[step_before]/_routes/_response.ts";
import * as $_lang_client_app_private_step_before_routes_service from "./routes/[lang]/client/app/private/[step_before]/_routes/_service.ts";
import * as $_lang_client_app_private_step_before_routes_types from "./routes/[lang]/client/app/private/[step_before]/_routes/_types.ts";
import * as $_lang_client_app_private_step_before_routes_utils from "./routes/[lang]/client/app/private/[step_before]/_routes/_utils.ts";
import * as $_lang_client_app_private_step_before_routes_validation from "./routes/[lang]/client/app/private/[step_before]/_routes/_validation.ts";
import * as $_lang_client_app_private_middleware from "./routes/[lang]/client/app/private/_middleware.ts";
import * as $_lang_client_app_private_routes_controller from "./routes/[lang]/client/app/private/_routes/_controller.ts";
import * as $_lang_client_app_private_routes_payload from "./routes/[lang]/client/app/private/_routes/_payload.ts";
import * as $_lang_client_app_private_routes_response from "./routes/[lang]/client/app/private/_routes/_response.ts";
import * as $_lang_client_app_private_routes_service from "./routes/[lang]/client/app/private/_routes/_service.ts";
import * as $_lang_client_app_private_routes_utils from "./routes/[lang]/client/app/private/_routes/_utils.ts";
import * as $_lang_client_app_private_routes_validation from "./routes/[lang]/client/app/private/_routes/_validation.ts";
import * as $_lang_client_app_private_index from "./routes/[lang]/client/app/private/index.tsx";
import * as $_lang_client_app_private_login from "./routes/[lang]/client/app/private/login.tsx";
import * as $_lang_client_app_private_services_middleware from "./routes/[lang]/client/app/private/services/_middleware.ts";
import * as $_lang_client_app_private_services_payment_routes_controller from "./routes/[lang]/client/app/private/services/payment/_routes/_controller.ts";
import * as $_lang_client_app_private_services_payment_routes_payload from "./routes/[lang]/client/app/private/services/payment/_routes/_payload.ts";
import * as $_lang_client_app_private_services_payment_routes_response from "./routes/[lang]/client/app/private/services/payment/_routes/_response.ts";
import * as $_lang_client_app_private_services_payment_routes_service from "./routes/[lang]/client/app/private/services/payment/_routes/_service.ts";
import * as $_lang_client_app_private_services_payment_routes_types from "./routes/[lang]/client/app/private/services/payment/_routes/_types.ts";
import * as $_lang_client_app_private_services_payment_routes_utils from "./routes/[lang]/client/app/private/services/payment/_routes/_utils.ts";
import * as $_lang_client_app_private_services_payment_routes_validation from "./routes/[lang]/client/app/private/services/payment/_routes/_validation.ts";
import * as $_lang_client_app_private_services_payment_index from "./routes/[lang]/client/app/private/services/payment/index.tsx";
import * as $_lang_client_app_private_services_payment_qr_routes_controller from "./routes/[lang]/client/app/private/services/payment_qr/_routes/_controller.ts";
import * as $_lang_client_app_private_services_payment_qr_routes_payload from "./routes/[lang]/client/app/private/services/payment_qr/_routes/_payload.ts";
import * as $_lang_client_app_private_services_payment_qr_routes_response from "./routes/[lang]/client/app/private/services/payment_qr/_routes/_response.ts";
import * as $_lang_client_app_private_services_payment_qr_routes_service from "./routes/[lang]/client/app/private/services/payment_qr/_routes/_service.ts";
import * as $_lang_client_app_private_services_payment_qr_routes_types from "./routes/[lang]/client/app/private/services/payment_qr/_routes/_types.ts";
import * as $_lang_client_app_private_services_payment_qr_routes_utils from "./routes/[lang]/client/app/private/services/payment_qr/_routes/_utils.ts";
import * as $_lang_client_app_private_services_payment_qr_routes_validation from "./routes/[lang]/client/app/private/services/payment_qr/_routes/_validation.ts";
import * as $_lang_client_app_private_services_payment_qr_index from "./routes/[lang]/client/app/private/services/payment_qr/index.tsx";
import * as $_lang_client_app_private_services_products_index from "./routes/[lang]/client/app/private/services/products/index.tsx";
import * as $_lang_client_app_private_services_protected_middleware from "./routes/[lang]/client/app/private/services/protected/_middleware.ts";
import * as $_lang_client_app_private_services_protected_index from "./routes/[lang]/client/app/private/services/protected/index.tsx";
import * as $_lang_client_app_private_services_transaction_routes_controller from "./routes/[lang]/client/app/private/services/transaction/_routes/_controller.ts";
import * as $_lang_client_app_private_services_transaction_routes_payload from "./routes/[lang]/client/app/private/services/transaction/_routes/_payload.ts";
import * as $_lang_client_app_private_services_transaction_routes_response from "./routes/[lang]/client/app/private/services/transaction/_routes/_response.ts";
import * as $_lang_client_app_private_services_transaction_routes_service from "./routes/[lang]/client/app/private/services/transaction/_routes/_service.ts";
import * as $_lang_client_app_private_services_transaction_routes_types from "./routes/[lang]/client/app/private/services/transaction/_routes/_types.ts";
import * as $_lang_client_app_private_services_transaction_routes_utils from "./routes/[lang]/client/app/private/services/transaction/_routes/_utils.ts";
import * as $_lang_client_app_private_services_transaction_routes_validation from "./routes/[lang]/client/app/private/services/transaction/_routes/_validation.ts";
import * as $_lang_client_app_private_services_transaction_index from "./routes/[lang]/client/app/private/services/transaction/index.tsx";
import * as $_lang_client_app_private_step_before from "./routes/[lang]/client/app/private/step_before.tsx";
import * as $_lang_client_app_public_services_license_routes_controller from "./routes/[lang]/client/app/public/services/license/_routes/_controller.ts";
import * as $_lang_client_app_public_services_license_routes_payload from "./routes/[lang]/client/app/public/services/license/_routes/_payload.ts";
import * as $_lang_client_app_public_services_license_routes_response from "./routes/[lang]/client/app/public/services/license/_routes/_response.ts";
import * as $_lang_client_app_public_services_license_routes_service from "./routes/[lang]/client/app/public/services/license/_routes/_service.ts";
import * as $_lang_client_app_public_services_license_routes_types from "./routes/[lang]/client/app/public/services/license/_routes/_types.ts";
import * as $_lang_client_app_public_services_license_routes_utils from "./routes/[lang]/client/app/public/services/license/_routes/_utils.ts";
import * as $_lang_client_app_public_services_license_routes_validation from "./routes/[lang]/client/app/public/services/license/_routes/_validation.ts";
import * as $_lang_client_app_public_services_license_index from "./routes/[lang]/client/app/public/services/license/index.tsx";
import * as $_lang_client_app_public_services_login_index from "./routes/[lang]/client/app/public/services/login/index.tsx";
import * as $_lang_index from "./routes/[lang]/index.tsx";
import * as $_lang_license from "./routes/[lang]/license.tsx";
import * as $_lang_web_routes_controller from "./routes/[lang]/web/_routes/_controller.ts";
import * as $_lang_web_routes_payload from "./routes/[lang]/web/_routes/_payload.ts";
import * as $_lang_web_routes_response from "./routes/[lang]/web/_routes/_response.ts";
import * as $_lang_web_routes_service from "./routes/[lang]/web/_routes/_service.ts";
import * as $_lang_web_routes_types from "./routes/[lang]/web/_routes/_types.ts";
import * as $_lang_web_routes_utils from "./routes/[lang]/web/_routes/_utils.ts";
import * as $_lang_web_routes_validation from "./routes/[lang]/web/_routes/_validation.ts";
import * as $_lang_web_index from "./routes/[lang]/web/index.tsx";
import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $_middleware from "./routes/_middleware.ts";
import * as $api_index from "./routes/api/index.ts";
import * as $api_joke from "./routes/api/joke.ts";
import * as $api_v1_protected_middleware from "./routes/api/v1/protected/_middleware.ts";
import * as $api_v1_protected_business_ws_index from "./routes/api/v1/protected/business/ws/index.ts";
import * as $api_v1_protected_index from "./routes/api/v1/protected/index.ts";
import * as $api_v1_public_business_dashboard_products_index from "./routes/api/v1/public/business/dashboard/products/index.ts";
import * as $api_v1_public_business_steps_register_index from "./routes/api/v1/public/business/steps/register/index.ts";
import * as $api_v1_public_business_ws_routes_controller from "./routes/api/v1/public/business/ws/_routes/_controller.ts";
import * as $api_v1_public_business_ws_routes_payload from "./routes/api/v1/public/business/ws/_routes/_payload.ts";
import * as $api_v1_public_business_ws_routes_response from "./routes/api/v1/public/business/ws/_routes/_response.ts";
import * as $api_v1_public_business_ws_routes_service from "./routes/api/v1/public/business/ws/_routes/_service.ts";
import * as $api_v1_public_business_ws_routes_types from "./routes/api/v1/public/business/ws/_routes/_types.ts";
import * as $api_v1_public_business_ws_routes_utils from "./routes/api/v1/public/business/ws/_routes/_utils.ts";
import * as $api_v1_public_business_ws_routes_validation from "./routes/api/v1/public/business/ws/_routes/_validation.ts";
import * as $api_v1_public_business_ws_routes_websockets_middlewares_fastifyApiRequest from "./routes/api/v1/public/business/ws/_routes/_websockets/_middlewares/fastifyApiRequest.ts";
import * as $api_v1_public_business_ws_routes_websockets_middlewares_index from "./routes/api/v1/public/business/ws/_routes/_websockets/_middlewares/index.ts";
import * as $api_v1_public_business_ws_routes_websockets_services from "./routes/api/v1/public/business/ws/_routes/_websockets/_services.ts";
import * as $api_v1_public_business_ws_routes_websockets_services_business_ping from "./routes/api/v1/public/business/ws/_routes/_websockets/_services/business.ping.ts";
import * as $api_v1_public_business_ws_routes_websockets_services_business_redirect_api from "./routes/api/v1/public/business/ws/_routes/_websockets/_services/business.redirect.api.ts";
import * as $api_v1_public_business_ws_routes_websockets_services_business_request_waiter_call from "./routes/api/v1/public/business/ws/_routes/_websockets/_services/business.request.waiter.call.ts";
import * as $api_v1_public_business_ws_routes_websockets_services_business_status_mobile from "./routes/api/v1/public/business/ws/_routes/_websockets/_services/business.status.mobile.ts";
import * as $api_v1_public_business_ws_index from "./routes/api/v1/public/business/ws/index.ts";
import * as $api_v1_public_business_ws_tokens_refresh_routes_controller from "./routes/api/v1/public/business/ws/tokens/refresh/_routes/_controller.ts";
import * as $api_v1_public_business_ws_tokens_refresh_routes_payload from "./routes/api/v1/public/business/ws/tokens/refresh/_routes/_payload.ts";
import * as $api_v1_public_business_ws_tokens_refresh_routes_response from "./routes/api/v1/public/business/ws/tokens/refresh/_routes/_response.ts";
import * as $api_v1_public_business_ws_tokens_refresh_routes_service from "./routes/api/v1/public/business/ws/tokens/refresh/_routes/_service.ts";
import * as $api_v1_public_business_ws_tokens_refresh_routes_types from "./routes/api/v1/public/business/ws/tokens/refresh/_routes/_types.ts";
import * as $api_v1_public_business_ws_tokens_refresh_routes_utils from "./routes/api/v1/public/business/ws/tokens/refresh/_routes/_utils.ts";
import * as $api_v1_public_business_ws_tokens_refresh_routes_validation from "./routes/api/v1/public/business/ws/tokens/refresh/_routes/_validation.ts";
import * as $api_v1_public_business_ws_tokens_refresh_index from "./routes/api/v1/public/business/ws/tokens/refresh/index.ts";
import * as $api_v1_public_client_steps_initialize_index from "./routes/api/v1/public/client/steps/initialize/index.ts";
import * as $api_v1_public_client_steps_payment_index from "./routes/api/v1/public/client/steps/payment/index.ts";
import * as $api_v1_public_client_steps_products_index from "./routes/api/v1/public/client/steps/products/index.ts";
import * as $api_v1_public_client_steps_transaction_index from "./routes/api/v1/public/client/steps/transaction/index.ts";
import * as $api_v1_public_oauth_callback_app_index from "./routes/api/v1/public/oauth/callback/app/index.ts";
import * as $api_v1_public_oauth_callback_web_index from "./routes/api/v1/public/oauth/callback/web/index.ts";
import * as $api_v1_public_oauth_session_index from "./routes/api/v1/public/oauth/session/index.ts";
import * as $greet_name_ from "./routes/greet/[name].tsx";
import * as $greet_middleware from "./routes/greet/_middleware.ts";
import * as $html from "./routes/html.tsx";
import * as $index from "./routes/index.tsx";
import * as $login from "./routes/login.tsx";
import * as $sitemap_xml from "./routes/sitemap.xml.ts";
import * as $hooks_useClientStore from "./islands/hooks/useClientStore.ts";
import * as $hooks_useRPCAPI from "./islands/hooks/useRPCAPI.ts";
import * as $hooks_useRPCAPIRequestList from "./islands/hooks/useRPCAPIRequestList.ts";
import * as $hooks_useRPCWebsockets from "./islands/hooks/useRPCWebsockets.ts";
import * as $hooks_useRPCWebsocketsRequestsList from "./islands/hooks/useRPCWebsocketsRequestsList.ts";
import * as $hooks_useTimeFormatter from "./islands/hooks/useTimeFormatter.ts";
import * as $providers_stores_websocketStore from "./islands/providers/stores/websocketStore.ts";
import * as $redirect_index from "./islands/redirect/index.tsx";
import * as $routes_global_GenericSelect from "./islands/routes/[global]/GenericSelect.tsx";
import * as $routes_global_QRScanner from "./islands/routes/[global]/QRScanner.tsx";
import * as $routes_global_QrSvg from "./islands/routes/[global]/QrSvg.tsx";
import * as $routes_global_ToggleSwitch from "./islands/routes/[global]/ToggleSwitch.tsx";
import * as $routes_lang_ViewLicenseForm from "./islands/routes/[lang]/ViewLicenseForm.tsx";
import * as $routes_lang_admin_Navbar from "./islands/routes/[lang]/admin/Navbar.tsx";
import * as $routes_lang_admin_View from "./islands/routes/[lang]/admin/View.tsx";
import * as $routes_lang_admin_ViewBusiness from "./islands/routes/[lang]/admin/ViewBusiness.tsx";
import * as $routes_lang_admin_ViewHome from "./islands/routes/[lang]/admin/ViewHome.tsx";
import * as $routes_lang_business_LogoNavbar from "./islands/routes/[lang]/business/LogoNavbar.tsx";
import * as $routes_lang_business_app_LogoNavbar from "./islands/routes/[lang]/business/app/LogoNavbar.tsx";
import * as $routes_lang_business_app_NavigationBar from "./islands/routes/[lang]/business/app/NavigationBar.tsx";
import * as $routes_lang_business_app_ViewLicenseForm from "./islands/routes/[lang]/business/app/ViewLicenseForm.tsx";
import * as $routes_lang_business_web_app_ViewPage from "./islands/routes/[lang]/business/web/app/ViewPage.tsx";
import * as $routes_lang_business_web_app_analitics_ViewPage from "./islands/routes/[lang]/business/web/app/analitics/ViewPage.tsx";
import * as $routes_lang_business_web_app_configurations_ViewPage from "./islands/routes/[lang]/business/web/app/configurations/ViewPage.tsx";
import * as $routes_lang_business_web_app_dashboard_ViewPage from "./islands/routes/[lang]/business/web/app/dashboard/ViewPage.tsx";
import * as $routes_lang_business_web_app_multibusiness_ViewPage from "./islands/routes/[lang]/business/web/app/multibusiness/ViewPage.tsx";
import * as $routes_lang_business_web_app_users_ViewPage from "./islands/routes/[lang]/business/web/app/users/ViewPage.tsx";
import * as $routes_lang_business_web_www_ButtonTrial from "./islands/routes/[lang]/business/web/www/ButtonTrial.tsx";
import * as $routes_lang_business_web_www_DoughnutChart from "./islands/routes/[lang]/business/web/www/DoughnutChart.tsx";
import * as $routes_lang_business_web_www_Footer from "./islands/routes/[lang]/business/web/www/Footer.tsx";
import * as $routes_lang_business_web_www_LineChart from "./islands/routes/[lang]/business/web/www/LineChart.tsx";
import * as $routes_lang_business_web_www_Tooltip from "./islands/routes/[lang]/business/web/www/Tooltip.tsx";
import * as $routes_lang_business_web_www_TrustedByCarousel from "./islands/routes/[lang]/business/web/www/TrustedByCarousel.tsx";
import * as $routes_lang_business_web_www_ViewGraph from "./islands/routes/[lang]/business/web/www/ViewGraph.tsx";
import * as $routes_lang_business_web_www_examples_graphs_HorizontalBarChart from "./islands/routes/[lang]/business/web/www/_examples/graphs/HorizontalBarChart.tsx";
import * as $routes_lang_business_web_www_examples_graphs_RadarChart from "./islands/routes/[lang]/business/web/www/_examples/graphs/RadarChart.tsx";
import * as $routes_lang_business_web_www_help_ViewHelp from "./islands/routes/[lang]/business/web/www/help/ViewHelp.tsx";
import * as $routes_lang_business_web_www_login_Form from "./islands/routes/[lang]/business/web/www/login/Form.tsx";
import * as $routes_lang_client_Barcode from "./islands/routes/[lang]/client/Barcode.tsx";
import * as $routes_lang_client_BasketButton from "./islands/routes/[lang]/client/BasketButton.tsx";
import * as $routes_lang_client_Counter from "./islands/routes/[lang]/client/Counter.tsx";
import * as $routes_lang_client_EmailField from "./islands/routes/[lang]/client/EmailField.tsx";
import * as $routes_lang_client_InfoModal from "./islands/routes/[lang]/client/InfoModal.tsx";
import * as $routes_lang_client_LangButton from "./islands/routes/[lang]/client/LangButton.tsx";
import * as $routes_lang_client_LogoNavbar from "./islands/routes/[lang]/client/LogoNavbar.tsx";
import * as $routes_lang_client_MenuModal from "./islands/routes/[lang]/client/MenuModal.tsx";
import * as $routes_lang_client_OrderButton from "./islands/routes/[lang]/client/OrderButton.tsx";
import * as $routes_lang_client_RedirectEmpyProducts from "./islands/routes/[lang]/client/RedirectEmpyProducts.tsx";
import * as $routes_lang_client_ShoppingNavbar from "./islands/routes/[lang]/client/ShoppingNavbar.tsx";
import * as $routes_lang_client_ShoppingTab from "./islands/routes/[lang]/client/ShoppingTab.tsx";
import * as $routes_lang_client_TicketProcesor from "./islands/routes/[lang]/client/TicketProcesor.tsx";
import * as $routes_lang_client_ViewInfoModal from "./islands/routes/[lang]/client/ViewInfoModal.tsx";
import * as $routes_lang_client_ViewMenuModal from "./islands/routes/[lang]/client/ViewMenuModal.tsx";
import * as $routes_lang_client_ViewWifiModal from "./islands/routes/[lang]/client/ViewWifiModal.tsx";
import * as $routes_lang_client_WifiModal from "./islands/routes/[lang]/client/WifiModal.tsx";
import * as $routes_lang_client_app_AppListenerCap from "./islands/routes/[lang]/client/app/AppListenerCap.tsx";
import * as $routes_lang_client_app_global_BackgroundConnectionVerify from "./islands/routes/[lang]/client/app/[_global]/BackgroundConnectionVerify.tsx";
import * as $routes_lang_client_app_global_LangButtonCSR from "./islands/routes/[lang]/client/app/[_global]/LangButtonCSR.tsx";
import * as $routes_lang_client_app_global_hooks_BackgroundConnectionVerify from "./islands/routes/[lang]/client/app/[_global]/hooks/BackgroundConnectionVerify.tsx";
import * as $routes_lang_client_app_global_websocket_WebsocketConnect from "./islands/routes/[lang]/client/app/[_global]/websocket/WebsocketConnect.tsx";
import * as $routes_lang_client_app_global_zustand_storeConnection from "./islands/routes/[lang]/client/app/[_global]/zustand/storeConnection.ts";
import * as $routes_lang_client_app_global_zustand_storeLang from "./islands/routes/[lang]/client/app/[_global]/zustand/storeLang.ts";
import * as $routes_lang_client_app_login_View from "./islands/routes/[lang]/client/app/[login]/View.tsx";
import * as $routes_lang_client_app_step_before_ButtonAutomatizedOrder from "./islands/routes/[lang]/client/app/[step_before]/ButtonAutomatizedOrder.tsx";
import * as $routes_lang_client_app_step_before_ButtonManualOrder from "./islands/routes/[lang]/client/app/[step_before]/ButtonManualOrder.tsx";
import * as $routes_lang_client_app_step_before_ButtonMenu from "./islands/routes/[lang]/client/app/[step_before]/ButtonMenu.tsx";
import * as $routes_lang_client_app_step_before_ButtonWifi from "./islands/routes/[lang]/client/app/[step_before]/ButtonWifi.tsx";
import * as $routes_lang_client_app_step_before_ViewStepBefore from "./islands/routes/[lang]/client/app/[step_before]/ViewStepBefore.tsx";
import * as $routes_lang_client_app_login_View_1 from "./islands/routes/[lang]/client/app/login/View.tsx";
import * as $routes_lang_client_app_payment_BankCardScanner from "./islands/routes/[lang]/client/app/payment/BankCardScanner.tsx";
import * as $routes_lang_client_app_payment_NextButton from "./islands/routes/[lang]/client/app/payment/NextButton.tsx";
import * as $routes_lang_client_app_payment_ProductsButton from "./islands/routes/[lang]/client/app/payment/ProductsButton.tsx";
import * as $routes_lang_client_app_payment_qr_NextButton from "./islands/routes/[lang]/client/app/payment_qr/NextButton.tsx";
import * as $routes_lang_client_app_payment_qr_QrOrder from "./islands/routes/[lang]/client/app/payment_qr/QrOrder.tsx";
import * as $routes_lang_client_app_payment_qr_TotalPriceOrder from "./islands/routes/[lang]/client/app/payment_qr/TotalPriceOrder.tsx";
import * as $routes_lang_client_app_payment_qr_View from "./islands/routes/[lang]/client/app/payment_qr/View.tsx";
import * as $routes_lang_client_app_products_BasketButton from "./islands/routes/[lang]/client/app/products/BasketButton.tsx";
import * as $routes_lang_client_app_products_BasketModal from "./islands/routes/[lang]/client/app/products/BasketModal.tsx";
import * as $routes_lang_client_app_products_NextButton from "./islands/routes/[lang]/client/app/products/NextButton.tsx";
import * as $routes_lang_client_app_products_ProductsPanel from "./islands/routes/[lang]/client/app/products/ProductsPanel.tsx";
import * as $routes_lang_client_app_products_TotalPriceToPay from "./islands/routes/[lang]/client/app/products/TotalPriceToPay.tsx";
import * as $routes_lang_client_app_public_services_ViewLicenseForm from "./islands/routes/[lang]/client/app/public/services/ViewLicenseForm.tsx";
import * as $routes_lang_client_app_transaction_OrderBarcode from "./islands/routes/[lang]/client/app/transaction/OrderBarcode.tsx";
import * as $routes_lang_client_app_transaction_PaymentButton from "./islands/routes/[lang]/client/app/transaction/PaymentButton.tsx";
import * as $routes_lang_client_app_transaction_ViewTransaction from "./islands/routes/[lang]/client/app/transaction/ViewTransaction.tsx";
import * as $routes_lang_client_zustand_storeCommon from "./islands/routes/[lang]/client/zustand/storeCommon.ts";
import * as $routes_lang_client_zustand_storeMenu from "./islands/routes/[lang]/client/zustand/storeMenu.ts";
import * as $routes_lang_client_zustand_storeMenuCategory from "./islands/routes/[lang]/client/zustand/storeMenuCategory.ts";
import * as $routes_lang_client_zustand_storeMenuCategoryPriceAdjustment from "./islands/routes/[lang]/client/zustand/storeMenuCategoryPriceAdjustment.ts";
import * as $routes_lang_client_zustand_storeMenuPriceAdjustment from "./islands/routes/[lang]/client/zustand/storeMenuPriceAdjustment.ts";
import * as $routes_lang_client_zustand_storeMenuSection from "./islands/routes/[lang]/client/zustand/storeMenuSection.ts";
import * as $routes_lang_client_zustand_storeProduct from "./islands/routes/[lang]/client/zustand/storeProduct.ts";
import * as $routes_lang_client_zustand_storeProductGroup from "./islands/routes/[lang]/client/zustand/storeProductGroup.ts";
import * as $routes_lang_client_zustand_storeProductGroupPriceAdjustment from "./islands/routes/[lang]/client/zustand/storeProductGroupPriceAdjustment.ts";
import * as $routes_lang_client_zustand_storeShopping from "./islands/routes/[lang]/client/zustand/storeShopping.ts";
import * as $utils_websockets from "./islands/utils/websockets.ts";
import type { Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/.well-known/assetlinks.json.ts": $_well_known_assetlinks_json,
    "./routes/[lang]/[license]/_routes/_controller.ts":
      $_lang_license_routes_controller,
    "./routes/[lang]/[license]/_routes/_payload.ts":
      $_lang_license_routes_payload,
    "./routes/[lang]/[license]/_routes/_response.ts":
      $_lang_license_routes_response,
    "./routes/[lang]/[license]/_routes/_service.ts":
      $_lang_license_routes_service,
    "./routes/[lang]/[license]/_routes/_types.ts": $_lang_license_routes_types,
    "./routes/[lang]/[license]/_routes/_utils.ts": $_lang_license_routes_utils,
    "./routes/[lang]/[license]/_routes/_validation.ts":
      $_lang_license_routes_validation,
    "./routes/[lang]/_middleware.ts": $_lang_middleware,
    "./routes/[lang]/admin/_middleware.ts": $_lang_admin_middleware,
    "./routes/[lang]/admin/_routes/_controller.ts":
      $_lang_admin_routes_controller,
    "./routes/[lang]/admin/_routes/_payload.ts": $_lang_admin_routes_payload,
    "./routes/[lang]/admin/_routes/_response.ts": $_lang_admin_routes_response,
    "./routes/[lang]/admin/_routes/_service.ts": $_lang_admin_routes_service,
    "./routes/[lang]/admin/_routes/_types.ts": $_lang_admin_routes_types,
    "./routes/[lang]/admin/_routes/_utils.ts": $_lang_admin_routes_utils,
    "./routes/[lang]/admin/_routes/_validation.ts":
      $_lang_admin_routes_validation,
    "./routes/[lang]/admin/index.tsx": $_lang_admin_index,
    "./routes/[lang]/app/_routes/_controller.ts": $_lang_app_routes_controller,
    "./routes/[lang]/app/_routes/_payload.ts": $_lang_app_routes_payload,
    "./routes/[lang]/app/_routes/_response.ts": $_lang_app_routes_response,
    "./routes/[lang]/app/_routes/_service.ts": $_lang_app_routes_service,
    "./routes/[lang]/app/_routes/_types.ts": $_lang_app_routes_types,
    "./routes/[lang]/app/_routes/_utils.ts": $_lang_app_routes_utils,
    "./routes/[lang]/app/_routes/_validation.ts": $_lang_app_routes_validation,
    "./routes/[lang]/app/index.tsx": $_lang_app_index,
    "./routes/[lang]/business/app/[license]/_routes/_controller.ts":
      $_lang_business_app_license_routes_controller,
    "./routes/[lang]/business/app/[license]/_routes/_payload.ts":
      $_lang_business_app_license_routes_payload,
    "./routes/[lang]/business/app/[license]/_routes/_response.ts":
      $_lang_business_app_license_routes_response,
    "./routes/[lang]/business/app/[license]/_routes/_service.ts":
      $_lang_business_app_license_routes_service,
    "./routes/[lang]/business/app/[license]/_routes/_types.ts":
      $_lang_business_app_license_routes_types,
    "./routes/[lang]/business/app/[license]/_routes/_utils.ts":
      $_lang_business_app_license_routes_utils,
    "./routes/[lang]/business/app/[license]/_routes/_validation.ts":
      $_lang_business_app_license_routes_validation,
    "./routes/[lang]/business/app/_middleware.ts":
      $_lang_business_app_middleware,
    "./routes/[lang]/business/app/employee/index.tsx":
      $_lang_business_app_employee_index,
    "./routes/[lang]/business/app/index.tsx": $_lang_business_app_index,
    "./routes/[lang]/business/app/license.tsx": $_lang_business_app_license,
    "./routes/[lang]/business/app/step_before.tsx":
      $_lang_business_app_step_before,
    "./routes/[lang]/business/web/app/_middleware.ts":
      $_lang_business_web_app_middleware,
    "./routes/[lang]/business/web/app/_routes/_controller.ts":
      $_lang_business_web_app_routes_controller,
    "./routes/[lang]/business/web/app/_routes/_payload.ts":
      $_lang_business_web_app_routes_payload,
    "./routes/[lang]/business/web/app/_routes/_response.ts":
      $_lang_business_web_app_routes_response,
    "./routes/[lang]/business/web/app/_routes/_service.ts":
      $_lang_business_web_app_routes_service,
    "./routes/[lang]/business/web/app/_routes/_types.ts":
      $_lang_business_web_app_routes_types,
    "./routes/[lang]/business/web/app/_routes/_utils.ts":
      $_lang_business_web_app_routes_utils,
    "./routes/[lang]/business/web/app/_routes/_validation.ts":
      $_lang_business_web_app_routes_validation,
    "./routes/[lang]/business/web/app/analitics/_routes/_controller.ts":
      $_lang_business_web_app_analitics_routes_controller,
    "./routes/[lang]/business/web/app/analitics/_routes/_payload.ts":
      $_lang_business_web_app_analitics_routes_payload,
    "./routes/[lang]/business/web/app/analitics/_routes/_response.ts":
      $_lang_business_web_app_analitics_routes_response,
    "./routes/[lang]/business/web/app/analitics/_routes/_service.ts":
      $_lang_business_web_app_analitics_routes_service,
    "./routes/[lang]/business/web/app/analitics/_routes/_types.ts":
      $_lang_business_web_app_analitics_routes_types,
    "./routes/[lang]/business/web/app/analitics/_routes/_utils.ts":
      $_lang_business_web_app_analitics_routes_utils,
    "./routes/[lang]/business/web/app/analitics/_routes/_validation.ts":
      $_lang_business_web_app_analitics_routes_validation,
    "./routes/[lang]/business/web/app/analitics/index.tsx":
      $_lang_business_web_app_analitics_index,
    "./routes/[lang]/business/web/app/configurations/_routes/_controller.ts":
      $_lang_business_web_app_configurations_routes_controller,
    "./routes/[lang]/business/web/app/configurations/_routes/_payload.ts":
      $_lang_business_web_app_configurations_routes_payload,
    "./routes/[lang]/business/web/app/configurations/_routes/_response.ts":
      $_lang_business_web_app_configurations_routes_response,
    "./routes/[lang]/business/web/app/configurations/_routes/_service.ts":
      $_lang_business_web_app_configurations_routes_service,
    "./routes/[lang]/business/web/app/configurations/_routes/_types.ts":
      $_lang_business_web_app_configurations_routes_types,
    "./routes/[lang]/business/web/app/configurations/_routes/_utils.ts":
      $_lang_business_web_app_configurations_routes_utils,
    "./routes/[lang]/business/web/app/configurations/_routes/_validation.ts":
      $_lang_business_web_app_configurations_routes_validation,
    "./routes/[lang]/business/web/app/configurations/index.tsx":
      $_lang_business_web_app_configurations_index,
    "./routes/[lang]/business/web/app/dashboard/_routes/_controller.ts":
      $_lang_business_web_app_dashboard_routes_controller,
    "./routes/[lang]/business/web/app/dashboard/_routes/_payload.ts":
      $_lang_business_web_app_dashboard_routes_payload,
    "./routes/[lang]/business/web/app/dashboard/_routes/_response.ts":
      $_lang_business_web_app_dashboard_routes_response,
    "./routes/[lang]/business/web/app/dashboard/_routes/_service.ts":
      $_lang_business_web_app_dashboard_routes_service,
    "./routes/[lang]/business/web/app/dashboard/_routes/_types.ts":
      $_lang_business_web_app_dashboard_routes_types,
    "./routes/[lang]/business/web/app/dashboard/_routes/_utils.ts":
      $_lang_business_web_app_dashboard_routes_utils,
    "./routes/[lang]/business/web/app/dashboard/_routes/_validation.ts":
      $_lang_business_web_app_dashboard_routes_validation,
    "./routes/[lang]/business/web/app/dashboard/analistics/index.tsx":
      $_lang_business_web_app_dashboard_analistics_index,
    "./routes/[lang]/business/web/app/dashboard/configuration/index.tsx":
      $_lang_business_web_app_dashboard_configuration_index,
    "./routes/[lang]/business/web/app/dashboard/index.tsx":
      $_lang_business_web_app_dashboard_index,
    "./routes/[lang]/business/web/app/dashboard/orders/index.tsx":
      $_lang_business_web_app_dashboard_orders_index,
    "./routes/[lang]/business/web/app/dashboard/reports/index.tsx":
      $_lang_business_web_app_dashboard_reports_index,
    "./routes/[lang]/business/web/app/dashboard/warehouse/index.tsx":
      $_lang_business_web_app_dashboard_warehouse_index,
    "./routes/[lang]/business/web/app/index.tsx": $_lang_business_web_app_index,
    "./routes/[lang]/business/web/app/multibusiness/_routes/_controller.ts":
      $_lang_business_web_app_multibusiness_routes_controller,
    "./routes/[lang]/business/web/app/multibusiness/_routes/_payload.ts":
      $_lang_business_web_app_multibusiness_routes_payload,
    "./routes/[lang]/business/web/app/multibusiness/_routes/_response.ts":
      $_lang_business_web_app_multibusiness_routes_response,
    "./routes/[lang]/business/web/app/multibusiness/_routes/_service.ts":
      $_lang_business_web_app_multibusiness_routes_service,
    "./routes/[lang]/business/web/app/multibusiness/_routes/_types.ts":
      $_lang_business_web_app_multibusiness_routes_types,
    "./routes/[lang]/business/web/app/multibusiness/_routes/_utils.ts":
      $_lang_business_web_app_multibusiness_routes_utils,
    "./routes/[lang]/business/web/app/multibusiness/_routes/_validation.ts":
      $_lang_business_web_app_multibusiness_routes_validation,
    "./routes/[lang]/business/web/app/multibusiness/index.tsx":
      $_lang_business_web_app_multibusiness_index,
    "./routes/[lang]/business/web/app/users/_routes/_controller.ts":
      $_lang_business_web_app_users_routes_controller,
    "./routes/[lang]/business/web/app/users/_routes/_payload.ts":
      $_lang_business_web_app_users_routes_payload,
    "./routes/[lang]/business/web/app/users/_routes/_response.ts":
      $_lang_business_web_app_users_routes_response,
    "./routes/[lang]/business/web/app/users/_routes/_service.ts":
      $_lang_business_web_app_users_routes_service,
    "./routes/[lang]/business/web/app/users/_routes/_types.ts":
      $_lang_business_web_app_users_routes_types,
    "./routes/[lang]/business/web/app/users/_routes/_utils.ts":
      $_lang_business_web_app_users_routes_utils,
    "./routes/[lang]/business/web/app/users/_routes/_validation.ts":
      $_lang_business_web_app_users_routes_validation,
    "./routes/[lang]/business/web/app/users/index.tsx":
      $_lang_business_web_app_users_index,
    "./routes/[lang]/business/web/www/_routes/_controller.ts":
      $_lang_business_web_www_routes_controller,
    "./routes/[lang]/business/web/www/_routes/_payload.ts":
      $_lang_business_web_www_routes_payload,
    "./routes/[lang]/business/web/www/_routes/_response.ts":
      $_lang_business_web_www_routes_response,
    "./routes/[lang]/business/web/www/_routes/_service.ts":
      $_lang_business_web_www_routes_service,
    "./routes/[lang]/business/web/www/_routes/_types.ts":
      $_lang_business_web_www_routes_types,
    "./routes/[lang]/business/web/www/_routes/_utils.ts":
      $_lang_business_web_www_routes_utils,
    "./routes/[lang]/business/web/www/_routes/_validation.ts":
      $_lang_business_web_www_routes_validation,
    "./routes/[lang]/business/web/www/about/index.tsx":
      $_lang_business_web_www_about_index,
    "./routes/[lang]/business/web/www/careers/index.tsx":
      $_lang_business_web_www_careers_index,
    "./routes/[lang]/business/web/www/contact/index.tsx":
      $_lang_business_web_www_contact_index,
    "./routes/[lang]/business/web/www/cookies/index.tsx":
      $_lang_business_web_www_cookies_index,
    "./routes/[lang]/business/web/www/help/index.tsx":
      $_lang_business_web_www_help_index,
    "./routes/[lang]/business/web/www/history/index.tsx":
      $_lang_business_web_www_history_index,
    "./routes/[lang]/business/web/www/index.tsx": $_lang_business_web_www_index,
    "./routes/[lang]/business/web/www/login/_routes/_controller.ts":
      $_lang_business_web_www_login_routes_controller,
    "./routes/[lang]/business/web/www/login/_routes/_payload.ts":
      $_lang_business_web_www_login_routes_payload,
    "./routes/[lang]/business/web/www/login/_routes/_response.ts":
      $_lang_business_web_www_login_routes_response,
    "./routes/[lang]/business/web/www/login/_routes/_service.ts":
      $_lang_business_web_www_login_routes_service,
    "./routes/[lang]/business/web/www/login/_routes/_types.ts":
      $_lang_business_web_www_login_routes_types,
    "./routes/[lang]/business/web/www/login/_routes/_utils.ts":
      $_lang_business_web_www_login_routes_utils,
    "./routes/[lang]/business/web/www/login/_routes/_validation.ts":
      $_lang_business_web_www_login_routes_validation,
    "./routes/[lang]/business/web/www/login/index.tsx":
      $_lang_business_web_www_login_index,
    "./routes/[lang]/business/web/www/partners/global/index.tsx":
      $_lang_business_web_www_partners_global_index,
    "./routes/[lang]/business/web/www/partners/local/index.tsx":
      $_lang_business_web_www_partners_local_index,
    "./routes/[lang]/business/web/www/pricing/index.tsx":
      $_lang_business_web_www_pricing_index,
    "./routes/[lang]/business/web/www/privacy/index.tsx":
      $_lang_business_web_www_privacy_index,
    "./routes/[lang]/business/web/www/status/index.tsx":
      $_lang_business_web_www_status_index,
    "./routes/[lang]/business/web/www/team/index.tsx":
      $_lang_business_web_www_team_index,
    "./routes/[lang]/business/web/www/terms/index.tsx":
      $_lang_business_web_www_terms_index,
    "./routes/[lang]/client/[step_before]/_routes/_controller.ts":
      $_lang_client_step_before_routes_controller,
    "./routes/[lang]/client/[step_before]/_routes/_payload.ts":
      $_lang_client_step_before_routes_payload,
    "./routes/[lang]/client/[step_before]/_routes/_response.ts":
      $_lang_client_step_before_routes_response,
    "./routes/[lang]/client/[step_before]/_routes/_service.ts":
      $_lang_client_step_before_routes_service,
    "./routes/[lang]/client/[step_before]/_routes/_types.ts":
      $_lang_client_step_before_routes_types,
    "./routes/[lang]/client/[step_before]/_routes/_utils.ts":
      $_lang_client_step_before_routes_utils,
    "./routes/[lang]/client/[step_before]/_routes/_validation.ts":
      $_lang_client_step_before_routes_validation,
    "./routes/[lang]/client/app/private/[step_before]/_routes/_controller.ts":
      $_lang_client_app_private_step_before_routes_controller,
    "./routes/[lang]/client/app/private/[step_before]/_routes/_payload.ts":
      $_lang_client_app_private_step_before_routes_payload,
    "./routes/[lang]/client/app/private/[step_before]/_routes/_response.ts":
      $_lang_client_app_private_step_before_routes_response,
    "./routes/[lang]/client/app/private/[step_before]/_routes/_service.ts":
      $_lang_client_app_private_step_before_routes_service,
    "./routes/[lang]/client/app/private/[step_before]/_routes/_types.ts":
      $_lang_client_app_private_step_before_routes_types,
    "./routes/[lang]/client/app/private/[step_before]/_routes/_utils.ts":
      $_lang_client_app_private_step_before_routes_utils,
    "./routes/[lang]/client/app/private/[step_before]/_routes/_validation.ts":
      $_lang_client_app_private_step_before_routes_validation,
    "./routes/[lang]/client/app/private/_middleware.ts":
      $_lang_client_app_private_middleware,
    "./routes/[lang]/client/app/private/_routes/_controller.ts":
      $_lang_client_app_private_routes_controller,
    "./routes/[lang]/client/app/private/_routes/_payload.ts":
      $_lang_client_app_private_routes_payload,
    "./routes/[lang]/client/app/private/_routes/_response.ts":
      $_lang_client_app_private_routes_response,
    "./routes/[lang]/client/app/private/_routes/_service.ts":
      $_lang_client_app_private_routes_service,
    "./routes/[lang]/client/app/private/_routes/_utils.ts":
      $_lang_client_app_private_routes_utils,
    "./routes/[lang]/client/app/private/_routes/_validation.ts":
      $_lang_client_app_private_routes_validation,
    "./routes/[lang]/client/app/private/index.tsx":
      $_lang_client_app_private_index,
    "./routes/[lang]/client/app/private/login.tsx":
      $_lang_client_app_private_login,
    "./routes/[lang]/client/app/private/services/_middleware.ts":
      $_lang_client_app_private_services_middleware,
    "./routes/[lang]/client/app/private/services/payment/_routes/_controller.ts":
      $_lang_client_app_private_services_payment_routes_controller,
    "./routes/[lang]/client/app/private/services/payment/_routes/_payload.ts":
      $_lang_client_app_private_services_payment_routes_payload,
    "./routes/[lang]/client/app/private/services/payment/_routes/_response.ts":
      $_lang_client_app_private_services_payment_routes_response,
    "./routes/[lang]/client/app/private/services/payment/_routes/_service.ts":
      $_lang_client_app_private_services_payment_routes_service,
    "./routes/[lang]/client/app/private/services/payment/_routes/_types.ts":
      $_lang_client_app_private_services_payment_routes_types,
    "./routes/[lang]/client/app/private/services/payment/_routes/_utils.ts":
      $_lang_client_app_private_services_payment_routes_utils,
    "./routes/[lang]/client/app/private/services/payment/_routes/_validation.ts":
      $_lang_client_app_private_services_payment_routes_validation,
    "./routes/[lang]/client/app/private/services/payment/index.tsx":
      $_lang_client_app_private_services_payment_index,
    "./routes/[lang]/client/app/private/services/payment_qr/_routes/_controller.ts":
      $_lang_client_app_private_services_payment_qr_routes_controller,
    "./routes/[lang]/client/app/private/services/payment_qr/_routes/_payload.ts":
      $_lang_client_app_private_services_payment_qr_routes_payload,
    "./routes/[lang]/client/app/private/services/payment_qr/_routes/_response.ts":
      $_lang_client_app_private_services_payment_qr_routes_response,
    "./routes/[lang]/client/app/private/services/payment_qr/_routes/_service.ts":
      $_lang_client_app_private_services_payment_qr_routes_service,
    "./routes/[lang]/client/app/private/services/payment_qr/_routes/_types.ts":
      $_lang_client_app_private_services_payment_qr_routes_types,
    "./routes/[lang]/client/app/private/services/payment_qr/_routes/_utils.ts":
      $_lang_client_app_private_services_payment_qr_routes_utils,
    "./routes/[lang]/client/app/private/services/payment_qr/_routes/_validation.ts":
      $_lang_client_app_private_services_payment_qr_routes_validation,
    "./routes/[lang]/client/app/private/services/payment_qr/index.tsx":
      $_lang_client_app_private_services_payment_qr_index,
    "./routes/[lang]/client/app/private/services/products/index.tsx":
      $_lang_client_app_private_services_products_index,
    "./routes/[lang]/client/app/private/services/protected/_middleware.ts":
      $_lang_client_app_private_services_protected_middleware,
    "./routes/[lang]/client/app/private/services/protected/index.tsx":
      $_lang_client_app_private_services_protected_index,
    "./routes/[lang]/client/app/private/services/transaction/_routes/_controller.ts":
      $_lang_client_app_private_services_transaction_routes_controller,
    "./routes/[lang]/client/app/private/services/transaction/_routes/_payload.ts":
      $_lang_client_app_private_services_transaction_routes_payload,
    "./routes/[lang]/client/app/private/services/transaction/_routes/_response.ts":
      $_lang_client_app_private_services_transaction_routes_response,
    "./routes/[lang]/client/app/private/services/transaction/_routes/_service.ts":
      $_lang_client_app_private_services_transaction_routes_service,
    "./routes/[lang]/client/app/private/services/transaction/_routes/_types.ts":
      $_lang_client_app_private_services_transaction_routes_types,
    "./routes/[lang]/client/app/private/services/transaction/_routes/_utils.ts":
      $_lang_client_app_private_services_transaction_routes_utils,
    "./routes/[lang]/client/app/private/services/transaction/_routes/_validation.ts":
      $_lang_client_app_private_services_transaction_routes_validation,
    "./routes/[lang]/client/app/private/services/transaction/index.tsx":
      $_lang_client_app_private_services_transaction_index,
    "./routes/[lang]/client/app/private/step_before.tsx":
      $_lang_client_app_private_step_before,
    "./routes/[lang]/client/app/public/services/license/_routes/_controller.ts":
      $_lang_client_app_public_services_license_routes_controller,
    "./routes/[lang]/client/app/public/services/license/_routes/_payload.ts":
      $_lang_client_app_public_services_license_routes_payload,
    "./routes/[lang]/client/app/public/services/license/_routes/_response.ts":
      $_lang_client_app_public_services_license_routes_response,
    "./routes/[lang]/client/app/public/services/license/_routes/_service.ts":
      $_lang_client_app_public_services_license_routes_service,
    "./routes/[lang]/client/app/public/services/license/_routes/_types.ts":
      $_lang_client_app_public_services_license_routes_types,
    "./routes/[lang]/client/app/public/services/license/_routes/_utils.ts":
      $_lang_client_app_public_services_license_routes_utils,
    "./routes/[lang]/client/app/public/services/license/_routes/_validation.ts":
      $_lang_client_app_public_services_license_routes_validation,
    "./routes/[lang]/client/app/public/services/license/index.tsx":
      $_lang_client_app_public_services_license_index,
    "./routes/[lang]/client/app/public/services/login/index.tsx":
      $_lang_client_app_public_services_login_index,
    "./routes/[lang]/index.tsx": $_lang_index,
    "./routes/[lang]/license.tsx": $_lang_license,
    "./routes/[lang]/web/_routes/_controller.ts": $_lang_web_routes_controller,
    "./routes/[lang]/web/_routes/_payload.ts": $_lang_web_routes_payload,
    "./routes/[lang]/web/_routes/_response.ts": $_lang_web_routes_response,
    "./routes/[lang]/web/_routes/_service.ts": $_lang_web_routes_service,
    "./routes/[lang]/web/_routes/_types.ts": $_lang_web_routes_types,
    "./routes/[lang]/web/_routes/_utils.ts": $_lang_web_routes_utils,
    "./routes/[lang]/web/_routes/_validation.ts": $_lang_web_routes_validation,
    "./routes/[lang]/web/index.tsx": $_lang_web_index,
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/_middleware.ts": $_middleware,
    "./routes/api/index.ts": $api_index,
    "./routes/api/joke.ts": $api_joke,
    "./routes/api/v1/protected/_middleware.ts": $api_v1_protected_middleware,
    "./routes/api/v1/protected/business/ws/index.ts":
      $api_v1_protected_business_ws_index,
    "./routes/api/v1/protected/index.ts": $api_v1_protected_index,
    "./routes/api/v1/public/business/dashboard/products/index.ts":
      $api_v1_public_business_dashboard_products_index,
    "./routes/api/v1/public/business/steps/register/index.ts":
      $api_v1_public_business_steps_register_index,
    "./routes/api/v1/public/business/ws/_routes/_controller.ts":
      $api_v1_public_business_ws_routes_controller,
    "./routes/api/v1/public/business/ws/_routes/_payload.ts":
      $api_v1_public_business_ws_routes_payload,
    "./routes/api/v1/public/business/ws/_routes/_response.ts":
      $api_v1_public_business_ws_routes_response,
    "./routes/api/v1/public/business/ws/_routes/_service.ts":
      $api_v1_public_business_ws_routes_service,
    "./routes/api/v1/public/business/ws/_routes/_types.ts":
      $api_v1_public_business_ws_routes_types,
    "./routes/api/v1/public/business/ws/_routes/_utils.ts":
      $api_v1_public_business_ws_routes_utils,
    "./routes/api/v1/public/business/ws/_routes/_validation.ts":
      $api_v1_public_business_ws_routes_validation,
    "./routes/api/v1/public/business/ws/_routes/_websockets/_middlewares/fastifyApiRequest.ts":
      $api_v1_public_business_ws_routes_websockets_middlewares_fastifyApiRequest,
    "./routes/api/v1/public/business/ws/_routes/_websockets/_middlewares/index.ts":
      $api_v1_public_business_ws_routes_websockets_middlewares_index,
    "./routes/api/v1/public/business/ws/_routes/_websockets/_services.ts":
      $api_v1_public_business_ws_routes_websockets_services,
    "./routes/api/v1/public/business/ws/_routes/_websockets/_services/business.ping.ts":
      $api_v1_public_business_ws_routes_websockets_services_business_ping,
    "./routes/api/v1/public/business/ws/_routes/_websockets/_services/business.redirect.api.ts":
      $api_v1_public_business_ws_routes_websockets_services_business_redirect_api,
    "./routes/api/v1/public/business/ws/_routes/_websockets/_services/business.request.waiter.call.ts":
      $api_v1_public_business_ws_routes_websockets_services_business_request_waiter_call,
    "./routes/api/v1/public/business/ws/_routes/_websockets/_services/business.status.mobile.ts":
      $api_v1_public_business_ws_routes_websockets_services_business_status_mobile,
    "./routes/api/v1/public/business/ws/index.ts":
      $api_v1_public_business_ws_index,
    "./routes/api/v1/public/business/ws/tokens/refresh/_routes/_controller.ts":
      $api_v1_public_business_ws_tokens_refresh_routes_controller,
    "./routes/api/v1/public/business/ws/tokens/refresh/_routes/_payload.ts":
      $api_v1_public_business_ws_tokens_refresh_routes_payload,
    "./routes/api/v1/public/business/ws/tokens/refresh/_routes/_response.ts":
      $api_v1_public_business_ws_tokens_refresh_routes_response,
    "./routes/api/v1/public/business/ws/tokens/refresh/_routes/_service.ts":
      $api_v1_public_business_ws_tokens_refresh_routes_service,
    "./routes/api/v1/public/business/ws/tokens/refresh/_routes/_types.ts":
      $api_v1_public_business_ws_tokens_refresh_routes_types,
    "./routes/api/v1/public/business/ws/tokens/refresh/_routes/_utils.ts":
      $api_v1_public_business_ws_tokens_refresh_routes_utils,
    "./routes/api/v1/public/business/ws/tokens/refresh/_routes/_validation.ts":
      $api_v1_public_business_ws_tokens_refresh_routes_validation,
    "./routes/api/v1/public/business/ws/tokens/refresh/index.ts":
      $api_v1_public_business_ws_tokens_refresh_index,
    "./routes/api/v1/public/client/steps/initialize/index.ts":
      $api_v1_public_client_steps_initialize_index,
    "./routes/api/v1/public/client/steps/payment/index.ts":
      $api_v1_public_client_steps_payment_index,
    "./routes/api/v1/public/client/steps/products/index.ts":
      $api_v1_public_client_steps_products_index,
    "./routes/api/v1/public/client/steps/transaction/index.ts":
      $api_v1_public_client_steps_transaction_index,
    "./routes/api/v1/public/oauth/callback/app/index.ts":
      $api_v1_public_oauth_callback_app_index,
    "./routes/api/v1/public/oauth/callback/web/index.ts":
      $api_v1_public_oauth_callback_web_index,
    "./routes/api/v1/public/oauth/session/index.ts":
      $api_v1_public_oauth_session_index,
    "./routes/greet/[name].tsx": $greet_name_,
    "./routes/greet/_middleware.ts": $greet_middleware,
    "./routes/html.tsx": $html,
    "./routes/index.tsx": $index,
    "./routes/login.tsx": $login,
    "./routes/sitemap.xml.ts": $sitemap_xml,
  },
  islands: {
    "./islands/hooks/useClientStore.ts": $hooks_useClientStore,
    "./islands/hooks/useRPCAPI.ts": $hooks_useRPCAPI,
    "./islands/hooks/useRPCAPIRequestList.ts": $hooks_useRPCAPIRequestList,
    "./islands/hooks/useRPCWebsockets.ts": $hooks_useRPCWebsockets,
    "./islands/hooks/useRPCWebsocketsRequestsList.ts":
      $hooks_useRPCWebsocketsRequestsList,
    "./islands/hooks/useTimeFormatter.ts": $hooks_useTimeFormatter,
    "./islands/providers/stores/websocketStore.ts":
      $providers_stores_websocketStore,
    "./islands/redirect/index.tsx": $redirect_index,
    "./islands/routes/[global]/GenericSelect.tsx": $routes_global_GenericSelect,
    "./islands/routes/[global]/QRScanner.tsx": $routes_global_QRScanner,
    "./islands/routes/[global]/QrSvg.tsx": $routes_global_QrSvg,
    "./islands/routes/[global]/ToggleSwitch.tsx": $routes_global_ToggleSwitch,
    "./islands/routes/[lang]/ViewLicenseForm.tsx": $routes_lang_ViewLicenseForm,
    "./islands/routes/[lang]/admin/Navbar.tsx": $routes_lang_admin_Navbar,
    "./islands/routes/[lang]/admin/View.tsx": $routes_lang_admin_View,
    "./islands/routes/[lang]/admin/ViewBusiness.tsx":
      $routes_lang_admin_ViewBusiness,
    "./islands/routes/[lang]/admin/ViewHome.tsx": $routes_lang_admin_ViewHome,
    "./islands/routes/[lang]/business/LogoNavbar.tsx":
      $routes_lang_business_LogoNavbar,
    "./islands/routes/[lang]/business/app/LogoNavbar.tsx":
      $routes_lang_business_app_LogoNavbar,
    "./islands/routes/[lang]/business/app/NavigationBar.tsx":
      $routes_lang_business_app_NavigationBar,
    "./islands/routes/[lang]/business/app/ViewLicenseForm.tsx":
      $routes_lang_business_app_ViewLicenseForm,
    "./islands/routes/[lang]/business/web/app/ViewPage.tsx":
      $routes_lang_business_web_app_ViewPage,
    "./islands/routes/[lang]/business/web/app/analitics/ViewPage.tsx":
      $routes_lang_business_web_app_analitics_ViewPage,
    "./islands/routes/[lang]/business/web/app/configurations/ViewPage.tsx":
      $routes_lang_business_web_app_configurations_ViewPage,
    "./islands/routes/[lang]/business/web/app/dashboard/ViewPage.tsx":
      $routes_lang_business_web_app_dashboard_ViewPage,
    "./islands/routes/[lang]/business/web/app/multibusiness/ViewPage.tsx":
      $routes_lang_business_web_app_multibusiness_ViewPage,
    "./islands/routes/[lang]/business/web/app/users/ViewPage.tsx":
      $routes_lang_business_web_app_users_ViewPage,
    "./islands/routes/[lang]/business/web/www/ButtonTrial.tsx":
      $routes_lang_business_web_www_ButtonTrial,
    "./islands/routes/[lang]/business/web/www/DoughnutChart.tsx":
      $routes_lang_business_web_www_DoughnutChart,
    "./islands/routes/[lang]/business/web/www/Footer.tsx":
      $routes_lang_business_web_www_Footer,
    "./islands/routes/[lang]/business/web/www/LineChart.tsx":
      $routes_lang_business_web_www_LineChart,
    "./islands/routes/[lang]/business/web/www/Tooltip.tsx":
      $routes_lang_business_web_www_Tooltip,
    "./islands/routes/[lang]/business/web/www/TrustedByCarousel.tsx":
      $routes_lang_business_web_www_TrustedByCarousel,
    "./islands/routes/[lang]/business/web/www/ViewGraph.tsx":
      $routes_lang_business_web_www_ViewGraph,
    "./islands/routes/[lang]/business/web/www/_examples/graphs/HorizontalBarChart.tsx":
      $routes_lang_business_web_www_examples_graphs_HorizontalBarChart,
    "./islands/routes/[lang]/business/web/www/_examples/graphs/RadarChart.tsx":
      $routes_lang_business_web_www_examples_graphs_RadarChart,
    "./islands/routes/[lang]/business/web/www/help/ViewHelp.tsx":
      $routes_lang_business_web_www_help_ViewHelp,
    "./islands/routes/[lang]/business/web/www/login/Form.tsx":
      $routes_lang_business_web_www_login_Form,
    "./islands/routes/[lang]/client/Barcode.tsx": $routes_lang_client_Barcode,
    "./islands/routes/[lang]/client/BasketButton.tsx":
      $routes_lang_client_BasketButton,
    "./islands/routes/[lang]/client/Counter.tsx": $routes_lang_client_Counter,
    "./islands/routes/[lang]/client/EmailField.tsx":
      $routes_lang_client_EmailField,
    "./islands/routes/[lang]/client/InfoModal.tsx":
      $routes_lang_client_InfoModal,
    "./islands/routes/[lang]/client/LangButton.tsx":
      $routes_lang_client_LangButton,
    "./islands/routes/[lang]/client/LogoNavbar.tsx":
      $routes_lang_client_LogoNavbar,
    "./islands/routes/[lang]/client/MenuModal.tsx":
      $routes_lang_client_MenuModal,
    "./islands/routes/[lang]/client/OrderButton.tsx":
      $routes_lang_client_OrderButton,
    "./islands/routes/[lang]/client/RedirectEmpyProducts.tsx":
      $routes_lang_client_RedirectEmpyProducts,
    "./islands/routes/[lang]/client/ShoppingNavbar.tsx":
      $routes_lang_client_ShoppingNavbar,
    "./islands/routes/[lang]/client/ShoppingTab.tsx":
      $routes_lang_client_ShoppingTab,
    "./islands/routes/[lang]/client/TicketProcesor.tsx":
      $routes_lang_client_TicketProcesor,
    "./islands/routes/[lang]/client/ViewInfoModal.tsx":
      $routes_lang_client_ViewInfoModal,
    "./islands/routes/[lang]/client/ViewMenuModal.tsx":
      $routes_lang_client_ViewMenuModal,
    "./islands/routes/[lang]/client/ViewWifiModal.tsx":
      $routes_lang_client_ViewWifiModal,
    "./islands/routes/[lang]/client/WifiModal.tsx":
      $routes_lang_client_WifiModal,
    "./islands/routes/[lang]/client/app/AppListenerCap.tsx":
      $routes_lang_client_app_AppListenerCap,
    "./islands/routes/[lang]/client/app/[_global]/BackgroundConnectionVerify.tsx":
      $routes_lang_client_app_global_BackgroundConnectionVerify,
    "./islands/routes/[lang]/client/app/[_global]/LangButtonCSR.tsx":
      $routes_lang_client_app_global_LangButtonCSR,
    "./islands/routes/[lang]/client/app/[_global]/hooks/BackgroundConnectionVerify.tsx":
      $routes_lang_client_app_global_hooks_BackgroundConnectionVerify,
    "./islands/routes/[lang]/client/app/[_global]/websocket/WebsocketConnect.tsx":
      $routes_lang_client_app_global_websocket_WebsocketConnect,
    "./islands/routes/[lang]/client/app/[_global]/zustand/storeConnection.ts":
      $routes_lang_client_app_global_zustand_storeConnection,
    "./islands/routes/[lang]/client/app/[_global]/zustand/storeLang.ts":
      $routes_lang_client_app_global_zustand_storeLang,
    "./islands/routes/[lang]/client/app/[login]/View.tsx":
      $routes_lang_client_app_login_View,
    "./islands/routes/[lang]/client/app/[step_before]/ButtonAutomatizedOrder.tsx":
      $routes_lang_client_app_step_before_ButtonAutomatizedOrder,
    "./islands/routes/[lang]/client/app/[step_before]/ButtonManualOrder.tsx":
      $routes_lang_client_app_step_before_ButtonManualOrder,
    "./islands/routes/[lang]/client/app/[step_before]/ButtonMenu.tsx":
      $routes_lang_client_app_step_before_ButtonMenu,
    "./islands/routes/[lang]/client/app/[step_before]/ButtonWifi.tsx":
      $routes_lang_client_app_step_before_ButtonWifi,
    "./islands/routes/[lang]/client/app/[step_before]/ViewStepBefore.tsx":
      $routes_lang_client_app_step_before_ViewStepBefore,
    "./islands/routes/[lang]/client/app/login/View.tsx":
      $routes_lang_client_app_login_View_1,
    "./islands/routes/[lang]/client/app/payment/BankCardScanner.tsx":
      $routes_lang_client_app_payment_BankCardScanner,
    "./islands/routes/[lang]/client/app/payment/NextButton.tsx":
      $routes_lang_client_app_payment_NextButton,
    "./islands/routes/[lang]/client/app/payment/ProductsButton.tsx":
      $routes_lang_client_app_payment_ProductsButton,
    "./islands/routes/[lang]/client/app/payment_qr/NextButton.tsx":
      $routes_lang_client_app_payment_qr_NextButton,
    "./islands/routes/[lang]/client/app/payment_qr/QrOrder.tsx":
      $routes_lang_client_app_payment_qr_QrOrder,
    "./islands/routes/[lang]/client/app/payment_qr/TotalPriceOrder.tsx":
      $routes_lang_client_app_payment_qr_TotalPriceOrder,
    "./islands/routes/[lang]/client/app/payment_qr/View.tsx":
      $routes_lang_client_app_payment_qr_View,
    "./islands/routes/[lang]/client/app/products/BasketButton.tsx":
      $routes_lang_client_app_products_BasketButton,
    "./islands/routes/[lang]/client/app/products/BasketModal.tsx":
      $routes_lang_client_app_products_BasketModal,
    "./islands/routes/[lang]/client/app/products/NextButton.tsx":
      $routes_lang_client_app_products_NextButton,
    "./islands/routes/[lang]/client/app/products/ProductsPanel.tsx":
      $routes_lang_client_app_products_ProductsPanel,
    "./islands/routes/[lang]/client/app/products/TotalPriceToPay.tsx":
      $routes_lang_client_app_products_TotalPriceToPay,
    "./islands/routes/[lang]/client/app/public/services/ViewLicenseForm.tsx":
      $routes_lang_client_app_public_services_ViewLicenseForm,
    "./islands/routes/[lang]/client/app/transaction/OrderBarcode.tsx":
      $routes_lang_client_app_transaction_OrderBarcode,
    "./islands/routes/[lang]/client/app/transaction/PaymentButton.tsx":
      $routes_lang_client_app_transaction_PaymentButton,
    "./islands/routes/[lang]/client/app/transaction/ViewTransaction.tsx":
      $routes_lang_client_app_transaction_ViewTransaction,
    "./islands/routes/[lang]/client/zustand/storeCommon.ts":
      $routes_lang_client_zustand_storeCommon,
    "./islands/routes/[lang]/client/zustand/storeMenu.ts":
      $routes_lang_client_zustand_storeMenu,
    "./islands/routes/[lang]/client/zustand/storeMenuCategory.ts":
      $routes_lang_client_zustand_storeMenuCategory,
    "./islands/routes/[lang]/client/zustand/storeMenuCategoryPriceAdjustment.ts":
      $routes_lang_client_zustand_storeMenuCategoryPriceAdjustment,
    "./islands/routes/[lang]/client/zustand/storeMenuPriceAdjustment.ts":
      $routes_lang_client_zustand_storeMenuPriceAdjustment,
    "./islands/routes/[lang]/client/zustand/storeMenuSection.ts":
      $routes_lang_client_zustand_storeMenuSection,
    "./islands/routes/[lang]/client/zustand/storeProduct.ts":
      $routes_lang_client_zustand_storeProduct,
    "./islands/routes/[lang]/client/zustand/storeProductGroup.ts":
      $routes_lang_client_zustand_storeProductGroup,
    "./islands/routes/[lang]/client/zustand/storeProductGroupPriceAdjustment.ts":
      $routes_lang_client_zustand_storeProductGroupPriceAdjustment,
    "./islands/routes/[lang]/client/zustand/storeShopping.ts":
      $routes_lang_client_zustand_storeShopping,
    "./islands/utils/websockets.ts": $utils_websockets,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
