version: '3.9'

volumes:
  seaweedfs_volume:
  seaweedfs_filer_data:

configs:
  settings_json:
    file: ./s3.json

networks:
  seaweedfs:
    driver: overlay

services:
  master:
    image: chrislusf/seaweedfs
    ports:
      - 9333:9333
      - 19333:19333
      - 9324:9324
    command: "master -ip=master -ip.bind=0.0.0.0"
    networks:
      - seaweedfs
  volume:
    image: chrislusf/seaweedfs
    ports:
      - 8080:8080
      - 18080:18080
      - 9325:9325
    command: 'volume -mserver="master:9333" -ip=volume -ip.bind=0.0.0.0 -port=8080 -max=100'
    volumes:
      - seaweedfs_volume:/data
    depends_on:
      - master
    networks:
      - seaweedfs
  filer:
    image: chrislusf/seaweedfs
    ports:
      - 8888:8888
      - 18888:18888
      - 9326:9326
    command: 'filer -master="master:9333" -ip=filer -ip.bind=0.0.0.0'
    tty: true
    stdin_open: true
    deploy:
      replicas: 1
    volumes:
      - seaweedfs_filer_data:/data/filerldb2
    depends_on:
      - master
      - volume
    networks:
      - seaweedfs
  s3:
    image: chrislusf/seaweedfs
    ports:
      - 8334:8334
    command: >
      s3 -filer="filer:8888" -ip.bind=0.0.0.0 -port.https=8334
      -key.file=/etc/seaweedfs/certs/server-key.pem
      -cert.file=/etc/seaweedfs/certs/server-cert.pem
      -config=/etc/seaweedfs/s3.json
    volumes:
      - ./certs:/etc/seaweedfs/certs:ro
      - ./s3.json:/etc/seaweedfs/s3.json:ro
    depends_on:
      - master
      - volume
      - filer
    restart: unless-stopped
    networks:
      - seaweedfs
  webdav:
    image: chrislusf/seaweedfs
    ports:
      - 7333:7333
    command: 'webdav -filer="filer:8888"'
    depends_on:
      - master
      - volume
      - filer
    networks:
      - seaweedfs