
services:
  fastify-internal:
    image: node:20-alpine
    working_dir: /app
    deploy:
      restart_policy:
        condition: on-failure
      labels:
        - "traefik.enable=true"
        - "traefik.docker.network=traefik-public"
        - "traefik.http.routers.fastify-api.rule=Host(`www.cafebuy.es`) && PathPrefix(`/fastify/api`)"
        - "traefik.http.routers.fastify-api.entrypoints=websecure"
        - "traefik.http.routers.fastify-api.tls=true"
        - "traefik.http.services.fastify-api.loadbalancer.server.port=3000"
        - "traefik.http.middlewares.fastify-api-strip.stripprefix.prefixes=/fastify/api"
        - "traefik.http.routers.fastify-api.middlewares=fastify-api-strip"

    #ports:
    #  - "8300:8300"
    command: sh -c "npm install && npm run dev"
    volumes:
      - ./src:/app/src
      - ./package.json:/app/package.json
      - ./package-lock.json:/app/package-lock.json
      - ./tsconfig.json:/app/tsconfig.json
      - ./prisma:/app/prisma
      - ./node_modules:/app/node_modules
    networks:
      - fresh_framework_network


networks:
  fresh_framework_network:
    external: true