name: Apply Docker Swarm Configs to VPS

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  deploy:
    if: false
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Upload and Create Docker Configs
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_KEY }}
          port: ${{ secrets.VPS_PORT || 22 }}
          script: |
            echo "=== Creating Docker Swarm Configs ==="
            
            # Define config mappings: "config_name:file_path"
            CONFIGS=(
              "tls_conf:/home/ubuntu/FreshStack/traefik/dynamic/tls.yaml"
            )
            
            # Function to create or update config
            create_config() {
              local config_name=$1
              local file_path=$2
              
              echo "Processing: $config_name -> $file_path"
              
              if [ ! -f "$file_path" ]; then
                echo "⚠️  File $file_path not found, skipping $config_name"
                return 1
              fi
              
              # Check if config already exists (configs are immutable)
              if docker config ls --format "{{.Name}}" | grep -q "^${config_name}$"; then
                echo "Config $config_name already exists, creating versioned copy..."
                timestamp=$(date +%Y%m%d_%H%M%S)
                versioned_name="${config_name}_${timestamp}"
                docker config create "$versioned_name" "$file_path"
                echo "✅ Created: $versioned_name"
              else
                docker config create "$config_name" "$file_path"
                echo "✅ Created: $config_name"
              fi
            }
            
            # Iterate through all configs
            for config_entry in "${CONFIGS[@]}"; do
              IFS=':' read -r config_name file_path <<< "$config_entry"
              create_config "$config_name" "$file_path"
              echo "---"
            done
            
            echo "=== Current Docker Configs ==="
            docker config ls
            
            echo "=== Process completed ==="